fix: fix hashmap thread unsafe
casbin/jcasbin pull request #294
Opened 2022-09-10 17:03 UTC by imp2002

2022-09-11 02:50 UTC, hsluoyz commented
@shijianjs @tangyang9464 plz review

2022-09-11 08:31 UTC, tangyang9464 requested changes

2022-09-11 08:31 UTC, tangyang9464 commented on src/main/java/org/casbin/jcasbin/util/BuiltInFunctions.java
> +        private static Map<String, Map<String, AviatorBoolean>> memorizedMap = Collections.synchronizedMap(new HashMap<>());
use ConcurrentHashMap

2022-09-11 09:41 UTC, tangyang9464 approved these changes

2022-09-11 11:28 UTC, damienmiheev commented
Maybe this is a good place to add a test for asynchronous enforcement?

2022-09-11 15:24 UTC, merged

2022-09-13 06:59 UTC, shijianjs commented
@hsluoyz @imp2002 
After 30 seconds of running the test code #292 , there are other problems.

jcasbin version: 1.28.2、1.29.0
exception: 
```
java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')

	at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1882)
	at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:1998)
	at java.base/java.util.HashMap.treeifyBin(HashMap.java:767)
	at java.base/java.util.HashMap.putVal(HashMap.java:639)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at org.casbin.jcasbin.util.BuiltInFunctions$GenerateGFunctionClass$1.variadicCall(BuiltInFunctions.java:382)
	at com.googlecode.aviator.runtime.function.AbstractVariadicFunction.call(AbstractVariadicFunction.java:71)
	at Script_1663051805038_59.execute0(Script_1663051805038_59:1)
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:44)
	at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:237)
	at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:519)
	at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:631)
	at com.fingard.rdc.avatar.auth.casbin.CasbinTest.lambda$parallelTest$5(CasbinTest.java:97)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```