feat: implement `FileAdapter` addPolicy(), removePolicy()
casbin/jcasbin pull request #391
Opened 2024-03-13 07:07 UTC by imp2002

2024-03-13 07:42 UTC, imp2002 commented
Because the previous unit tests defaulted to a File Adapter that didn't implement `addPolicy()` and `removePolicy()`, ignoring the impact of autoSave, implementing `addPolicy()` and `removePolicy()` now results in inconsistent expect. Therefore, it is necessary to modify the previous tests.

2024-03-13 14:12 UTC, hsluoyz commented
@imp2002 you can keep that existing test in AutoSave OFF mode. Then add a new test case which enables AutoSave

2024-03-17 15:57 UTC, hsluoyz requested changes

2024-03-17 15:57 UTC, hsluoyz commented on src/test/java/org/casbin/jcasbin/main/EnforcerUnitTest.java
> +        e.enableAutoSave(false);
For this CSV adapter, set AutoSave to false by default. Only call `e.enableAutoSave(true)` to enable

2024-03-18 12:48 UTC, hsluoyz approved these changes

2024-03-18 12:48 UTC, merged